# Generated by Django 4.0.6 on 2024-08-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_remove_store_address_store_recommended_stores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storegroup',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
