# Generated by Django 4.0.6 on 2024-08-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_storegroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storegroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='storegroup',
            name='stores',
            field=models.ManyToManyField(related_name='store_groups', to='stores.store'),
        ),
    ]
